
version: '2.1'
services:
  #docker-compose build image
  image:
    build:
      context: .
      dockerfile: Dockerfile
      args:
      - IMAGE_ARG_FILESERVER=${IMAGE_ARG_FILESERVER}
      #- IMAGE_ARG_FILESERVER=${IMAGE_ARG_FILESERVER:-http://fileserver.infra.top}
    image: ${IMAGE_PREFIX:-cirepo/}${IMAGE_NAME:-nix}:${IMAGE_TAG:-2.2.1-centos}
